GET http://localhost:3000/subscribers
###

GET http://localhost:3000/subscribers/5e7ba496413dcf4c18c2c778
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "makus7ssssss",
    "subscribedToChannel" :"notatkaaa"
}
###

DELETE http://localhost:3000/subscribers/5e7ba496413dcf4c18c2c778
###

PATCH http://localhost:3000/subscribers/5e7ba553413dcf4c18c2c77a
Content-Type: application/json

{
    "name": "makuss4444"
}